/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param anyTypeProperty 
 * @param arrayProp test array in 3.1 spec
 * @param refArrayPrefixItems An item that was added to the queue. 
 */
@Serializable

data class AnyTypeTest (

    @SerialName(value = "any_type_property") val anyTypeProperty: kotlin.Any? = null,

    /* test array in 3.1 spec */
    @SerialName(value = "array_prop") val arrayProp: kotlin.collections.List<kotlin.String>? = null,

    /* An item that was added to the queue.  */
    @SerialName(value = "ref_array_prefix_items") val refArrayPrefixItems: kotlin.collections.List<kotlin.Any>? = null

) {


}

