/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import com.codingfeline.openapi.kmp.models.Animal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param color 
 * @param breed 
 */
@Serializable

@SerialName(value = "Dog")
data class Dog (

    @SerialName(value = "color") override val color: kotlin.String? = "red",

    @SerialName(value = "breed") val breed: kotlin.String? = null

) : Animal() {


}

