/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import com.codingfeline.openapi.kmp.models.FakeWebhooksSourcesDeletedPostRequestEvent

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * inline schema in webhooks
 *
 * @param eventTimestamp 
 * @param eventType 
 * @param event 
 */
@Serializable

data class FakeWebhooksSourcesDeletedPostRequest (

    @SerialName(value = "event_timestamp") @Required val eventTimestamp: kotlinx.datetime.Instant,

    @SerialName(value = "event_type") @Required val eventType: kotlin.String,

    @SerialName(value = "event") @Required val event: FakeWebhooksSourcesDeletedPostRequestEvent

) {


}

