/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.ktor.models.ArrayOfSameRef
import com.codingfeline.openapi.ktor.models.Tag

class ArrayOfSameRefTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ArrayOfSameRef
        //val modelInstance = ArrayOfSameRef()

        // to test the property `arrayFooOne`
        should("test arrayFooOne") {
            // uncomment below to test the property
            //modelInstance.arrayFooOne shouldBe ("TODO")
        }

        // to test the property `arrayFooTwo`
        should("test arrayFooTwo") {
            // uncomment below to test the property
            //modelInstance.arrayFooTwo shouldBe ("TODO")
        }

        // to test the property `arrayFooThree`
        should("test arrayFooThree") {
            // uncomment below to test the property
            //modelInstance.arrayFooThree shouldBe ("TODO")
        }

    }
}
