/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.ktor.models.CircularReference3
import com.codingfeline.openapi.ktor.models.CircularReference1

class CircularReference3Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of CircularReference3
        //val modelInstance = CircularReference3()

        // to test the property `prop1`
        should("test prop1") {
            // uncomment below to test the property
            //modelInstance.prop1 shouldBe ("TODO")
        }

    }
}
