/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.ktor.models.FakeWebhooksSourcesDeletedPostRequest
import com.codingfeline.openapi.ktor.models.FakeWebhooksSourcesDeletedPostRequestEvent

class FakeWebhooksSourcesDeletedPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FakeWebhooksSourcesDeletedPostRequest
        //val modelInstance = FakeWebhooksSourcesDeletedPostRequest()

        // to test the property `eventTimestamp`
        should("test eventTimestamp") {
            // uncomment below to test the property
            //modelInstance.eventTimestamp shouldBe ("TODO")
        }

        // to test the property `eventType`
        should("test eventType") {
            // uncomment below to test the property
            //modelInstance.eventType shouldBe ("TODO")
        }

        // to test the property `event`
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

    }
}
