/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.ktor.models.OneOfStringOrInt

class OneOfStringOrIntTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OneOfStringOrInt
        //val modelInstance = OneOfStringOrInt()

    }
}
