/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.apis.DefaultApi
import com.codingfeline.openapi.kmp.models.FakeWebhooksSourcesDeletedPostRequest

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test fakeWebhooksSourcesDeletedPost
        should("test fakeWebhooksSourcesDeletedPost") {
            // uncomment below to test fakeWebhooksSourcesDeletedPost
            //val fakeWebhooksSourcesDeletedPostRequest : FakeWebhooksSourcesDeletedPostRequest =  // FakeWebhooksSourcesDeletedPostRequest | 
            //apiInstance.fakeWebhooksSourcesDeletedPost(fakeWebhooksSourcesDeletedPostRequest)
        }

    }
}
