/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.Animal

class AnimalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Animal
        //val modelInstance = Animal()

        // to test the property `color`
        should("test color") {
            // uncomment below to test the property
            //modelInstance.color shouldBe ("TODO")
        }

    }
}
