/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.AnyTypeTest

class AnyTypeTestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnyTypeTest
        //val modelInstance = AnyTypeTest()

        // to test the property `anyTypeProperty`
        should("test anyTypeProperty") {
            // uncomment below to test the property
            //modelInstance.anyTypeProperty shouldBe ("TODO")
        }

        // to test the property `arrayProp` - test array in 3.1 spec
        should("test arrayProp") {
            // uncomment below to test the property
            //modelInstance.arrayProp shouldBe ("TODO")
        }

        // to test the property `refArrayPrefixItems` - An item that was added to the queue. 
        should("test refArrayPrefixItems") {
            // uncomment below to test the property
            //modelInstance.refArrayPrefixItems shouldBe ("TODO")
        }

    }
}
