/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.Cat
import com.codingfeline.openapi.kmp.models.Animal

class CatTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Cat
        //val modelInstance = Cat()

        // to test the property `declawed`
        should("test declawed") {
            // uncomment below to test the property
            //modelInstance.declawed shouldBe ("TODO")
        }

    }
}
