/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.CircularReference1
import com.codingfeline.openapi.kmp.models.CircularReference2

class CircularReference1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of CircularReference1
        //val modelInstance = CircularReference1()

        // to test the property `prop1`
        should("test prop1") {
            // uncomment below to test the property
            //modelInstance.prop1 shouldBe ("TODO")
        }

    }
}
