/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.Dog
import com.codingfeline.openapi.kmp.models.Animal

class DogTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Dog
        //val modelInstance = Dog()

        // to test the property `breed`
        should("test breed") {
            // uncomment below to test the property
            //modelInstance.breed shouldBe ("TODO")
        }

    }
}
