/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.SelfReferenceAdditionalProperties

class SelfReferenceAdditionalPropertiesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SelfReferenceAdditionalProperties
        //val modelInstance = SelfReferenceAdditionalProperties()

        // to test the property `dummy`
        should("test dummy") {
            // uncomment below to test the property
            //modelInstance.dummy shouldBe ("TODO")
        }

    }
}
