/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.kmp.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.kmp.models.SimpleModelWithArrayProperty

class SimpleModelWithArrayPropertyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SimpleModelWithArrayProperty
        //val modelInstance = SimpleModelWithArrayProperty()

        // to test the property `arrayOfStrings`
        should("test arrayOfStrings") {
            // uncomment below to test the property
            //modelInstance.arrayOfStrings shouldBe ("TODO")
        }

    }
}
