/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.retrofit.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.retrofit.models.FakeWebhooksSourcesDeletedPostRequestEvent

class FakeWebhooksSourcesDeletedPostRequestEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FakeWebhooksSourcesDeletedPostRequestEvent
        //val modelInstance = FakeWebhooksSourcesDeletedPostRequestEvent()

        // to test the property `eventId`
        should("test eventId") {
            // uncomment below to test the property
            //modelInstance.eventId shouldBe ("TODO")
        }

    }
}
