/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.retrofit.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.codingfeline.openapi.retrofit.models.SelfReferenceOneOf

class SelfReferenceOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SelfReferenceOneOf
        //val modelInstance = SelfReferenceOneOf()

    }
}
