/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.retrofit.models

import com.codingfeline.openapi.retrofit.models.Animal

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param color 
 * @param declawed 
 */
@Serializable

@SerialName(value = "Cat")
data class Cat (

    @SerialName(value = "color")
    override val color: kotlin.String? = "red",

    @SerialName(value = "declawed")
    val declawed: kotlin.Boolean? = null

) : Animal() {


}

