/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.retrofit.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param arrayOfStrings 
 */
@Serializable

data class SimpleModelWithArrayProperty (

    @SerialName(value = "arrayOfStrings")
    val arrayOfStrings: kotlin.collections.List<kotlin.String>

) {


}

