/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * 
 *
 * @param className 
 * @param color 
 */
@Serializable


@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "className")
sealed class Animal {

    @SerialName(value = "className")
    abstract val className: kotlin.String
    @SerialName(value = "color")
    abstract val color: kotlin.String?

}

