/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import com.codingfeline.openapi.ktor.models.Tag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param arrayFooOne 
 * @param arrayFooTwo 
 * @param arrayFooThree 
 */
@Serializable

data class ArrayOfSameRef (

    @SerialName(value = "arrayFooOne")
    val arrayFooOne: kotlin.collections.List<Tag>? = null,

    @SerialName(value = "arrayFooTwo")
    val arrayFooTwo: kotlin.collections.List<Tag>? = null,

    @SerialName(value = "arrayFooThree")
    val arrayFooThree: kotlin.collections.List<Tag>? = null

) {


}

