/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import com.codingfeline.openapi.ktor.models.Animal

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param className 
 * @param color 
 * @param breed 
 */
@Serializable

data class Dog (

    @SerialName(value = "className")
    override val className: kotlin.String,

    @SerialName(value = "color")
    override val color: kotlin.String? = "red",

    @SerialName(value = "breed")
    val breed: kotlin.String? = null

) : Animal() {


}

