/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models

import com.codingfeline.openapi.ktor.models.FakeWebhooksSourcesDeletedPostRequestEvent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * inline schema in webhooks
 *
 * @param eventTimestamp 
 * @param eventType 
 * @param event 
 */
@Serializable

data class FakeWebhooksSourcesDeletedPostRequest (

    @Contextual @SerialName(value = "event_timestamp")
    val eventTimestamp: kotlinx.datetime.Instant,

    @SerialName(value = "event_type")
    val eventType: kotlin.String,

    @SerialName(value = "event")
    val event: FakeWebhooksSourcesDeletedPostRequestEvent

) {


}

