/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.codingfeline.openapi.ktor.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param dummy 
 */
@Serializable

data class SelfReferenceAdditionalProperties (

    @SerialName(value = "dummy")
    val dummy: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()() {


}

